<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Create</title>
    <script type="text/javascript" src="/javascript.js"></script>
    </head>
<body>
<textarea id="code_snippet">// write your code here</textarea>
<br>
<Label>Time Restriction (Seconds) <input id="time_restriction" type="text"/></Label>
<br>
<Label>Views Restriction <input id="views_restriction" type="text"/></Label>
<br>
<button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>
</html>